2015-10-01 08:02:48,666 - error_log - ERROR - Image not exists
Traceback (most recent call last):
  File "/root/test_scripts/heat_migration/os_defs.py", line 371, in image_exists
    image = images.next()
StopIteration
2015-10-01 08:03:55,293 - error_log - ERROR - Image not exists
Traceback (most recent call last):
  File "/root/test_scripts/heat_migration/os_defs.py", line 371, in image_exists
    image = images.next()
StopIteration
